Repository ToucanToco/peakina, pull requests merged in 2019-08, with the labels that each got.

#3 Various improvements (→ to use peakina in toucantoco backend)
  Makefile
  README.md
  peakina/__init__.py
  peakina/cache.py
  peakina/datasource.py
  peakina/helpers.py
  peakina/io/fetcher.py
  peakina/io/ftp/ftp_utils.py
  peakina/readers/__init__.py
  peakina/readers/json.py
  peakina/readers/xml.py
  setup.cfg
  tests/fixtures/empty.csv
  tests/fixtures/fixture.json
  tests/io/ftp/test_ftp_utils.py
  tests/io/local/test_file_fetcher.py
  tests/test_datasource.py
  tests/test_fetch.py
  tests/test_helpers.py
Labels: enhancement, need review

#4 excel :: allow "encoding" kwarg
  peakina/helpers.py
  setup.cfg
  tests/test_helpers.py
Labels: bug

#6 excel :: allow legit "decimal" parameter
  peakina/helpers.py
  tests/test_datasource.py
  tests/test_helpers.py
Labels: bug

#5 Feature :: Add parquet support
  peakina/__init__.py
  peakina/datasource.py
  peakina/helpers.py
  setup.cfg
  tests/fixtures/userdata.parquet
  tests/test_datasource.py
  tests/test_helpers.py
Labels: enhancement

#7 datasource :: add get metadata
  peakina/datasource.py
  peakina/helpers.py
  setup.cfg
  tests/test_datasource.py
Labels: enhancement

#8 Fix :: Handle unexpected errors for HTTP mtime
  peakina/io/http/http_fetcher.py
  setup.cfg
  tests/io/http/test_http_fetcher.py
Labels: bug, need review

#9 allow https datasources even insecure
  peakina/io/http/http_fetcher.py
  setup.cfg
Labels: bug

#10 Fix :: Dont return metadata when match is enabled
  peakina/datasource.py
  setup.cfg
  tests/test_datasource.py
Labels: bug
