Repository ToucanToco/peakina, pull requests merged in 2019-11, with the labels that each got.

#19 [http] Use datasource's `fetcher_kwargs`
  peakina/io/http/http_fetcher.py
  tests/io/http/test_http_fetcher.py
Labels: bug, need review

#23 [https] add option to check SSL certificates
  peakina/io/http/http_fetcher.py
  setup.cfg
  tests/fixtures/dummy_cert.crt
  tests/io/http/test_http_fetcher.py
Labels: enhancement, need review

#24 v0.4.0
  CHANGELOG.md
  setup.cfg
Labels: need review, release

#25 Update CHANGELOG.md
  CHANGELOG.md
Labels: doc, need review
