Repository ToucanToco/peakina, pull requests merged in 2020-01, with the labels that each got.

#26 [doc] use README to populate long_description package field
  setup.cfg
Labels: doc, need review

#22 Put only peakina package in site-packages (no tests/)
  setup.cfg
Labels: conventions

#27 [doc] Update README.md
  README.md
Labels: doc
