Repository ToucanToco/peakina, pull requests merged in 2022-04, with the labels that each got.

#111 fix: ftp & kwargs for excel
  peakina/io/ftp/ftp_utils.py
  peakina/readers/excel.py
  tests/io/ftp/test_ftp_utils.py
Labels: bug

#126 build(deps): unpin pandas
  peakina/readers/csv.py
  poetry.lock
  pyproject.toml
Labels: dependencies

#125 refactor: remove useless extra params for `read_excel`
  peakina/helpers.py
  tests/test_helpers.py
Labels: refactoring

#89 feat: get version from the package
  peakina/__init__.py
Labels: enhancement

#127 refactor: switch from `error_bad_lines` to `on_bad_lines`
  peakina/helpers.py
  peakina/readers/csv.py
Labels: refactoring

#132 fix(csv): use proper encoding and fix lines number in `get_metadata`
  peakina/datasource.py
  peakina/readers/csv.py
  tests/fixtures/encoded_western_clrf_short.csv
  tests/fixtures/encoded_western_short.csv
  tests/fixtures/trailing_newline.csv
  tests/test_datasource.py
Labels: bug
